python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 2 --g 2 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 2 --g 3 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 2 --g 4 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 2 --g 5 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 2 --g 6 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 2 --g 7 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 2 --g 8 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 2 --g 9 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 3 --g 2 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 3 --g 3 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 3 --g 4 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 3 --g 5 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 3 --g 6 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 3 --g 7 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 3 --g 8 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 3 --g 9 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 4 --g 2 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 4 --g 3 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 4 --g 4 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 4 --g 5 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 4 --g 6 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 4 --g 7 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 4 --g 8 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 4 --g 9 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 5 --g 2 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 5 --g 3 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 5 --g 4 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 5 --g 5 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 5 --g 6 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 5 --g 7 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 5 --g 8 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 5 --g 9 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 6 --g 2 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 6 --g 3 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 6 --g 4 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 6 --g 5 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 6 --g 6 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 6 --g 7 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 6 --g 8 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 6 --g 9 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 7 --g 2 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 7 --g 3 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 7 --g 4 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 7 --g 5 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 7 --g 6 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 7 --g 7 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 7 --g 8 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 7 --g 9 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 8 --g 2 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 8 --g 3 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 8 --g 4 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 8 --g 5 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 8 --g 6 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 8 --g 7 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 8 --g 8 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 8 --g 9 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 9 --g 2 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 9 --g 3 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 9 --g 4 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 9 --g 5 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 9 --g 6 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 9 --g 7 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 9 --g 8 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 9 --g 9 &&
