python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 10 --g 10 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 10 --g 20 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 10 --g 30 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 10 --g 40 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 10 --g 50 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 20 --g 10 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 20 --g 20 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 20 --g 30 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 20 --g 40 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 20 --g 50 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 30 --g 10 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 30 --g 20 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 30 --g 30 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 30 --g 40 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 30 --g 50 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 40 --g 10 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 40 --g 20 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 40 --g 30 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 40 --g 40 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 40 --g 50 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 50 --g 10 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 50 --g 20 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 50 --g 30 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 50 --g 40 &&
python main.py --network ./datasets/real/walmart/network.hyp --algorithm EPA --k 50 --g 50 &&
